version: '3'
services:
  web:
    container_name: personal-website
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8993:80"
    volumes:
      - ./website:/usr/share/nginx/html
    command: nginx -g 'daemon off;'
