version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8993:80"
    volumes:
      - ./website:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    command: nginx -g 'daemon on;'
