name: Push to server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ssh-into-remote:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /srv/disk/Appdata/personal-website
            git pull
            docker compose up -d